config/routes.rb
Rails.application.routes.draw do

  resources :posts do
    post 'add' => 'likes#create'
    delete '/add' => 'likes#destroy'
  end

  get 'users/show'

  devise_scope :user do
    get '/users/sign_in' => 'users/sessions#new'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :users, :controllers => {
      sessions: 'users/sessions'
  }

  as :user do
    get '/posts',:to => 'devise/registrations#edit',:as => :user_root
  end

  root to: 'home#top'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post, optional: true
  belongs_to :user, optional: true
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :authenticate_user!
    before_action :set_like

    def create
        user = current_user
        post = Post.find(params[:post_id])
        like = Like.create(user_id: user.id, post_id: post.id)
    end
    def destroy
        user = current_user
        post = Post.find(params[:post_id])
        like = Like.find_by(user_id: user.id, post_id: post.id)
        like.delete
    end

    private
    def set_like
        @post = Post.find(params[:post_id])
    end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<% if post.liked_by?(current_user) %>
    <%= link_to(post_add_path(post), method: :delete, remote: true, id: :"like-button-#{post.id}") do %>
        <i class="fa-lg fas fa-heart icon-btn liked"></i>
    <% end %>
<% else %>
    <%= link_to(post_add_path(post), method: :post, remote: true, id: :"like-button-#{post.id}") do %>
        <i class="fa-lg fas fa-heart icon-btn not-like"></i>
    <% end %>
<% end %>

app/views/likes/create.js.erb
$('#like-btn-<%= @post.id %>').html("<%= escape_javascript(render partial: "likes/like", locals: { post: @post }) %>");

app/views/likes/destroy.js.erb
$('#like-btn-<%= @post.id %>').html("<%= escape_javascript(render partial: "likes/like", locals: { post: @post }) %>");