config/routes.rb
Rails.application.routes.draw do

  resources :posts do
    post 'add' => 'likes#create'
    delete '/add' => 'likes#destroy'
  end

  get 'users/show'

  devise_scope :user do
    get '/users/sign_in' => 'users/sessions#new'
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :users, :controllers => {
      sessions: 'users/sessions'
  }

  as :user do
    get '/posts',:to => 'devise/registrations#edit',:as => :user_root
  end

  root to: 'home#top'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_flashes.html.erb
<% flash.each do |key,value| %>
    <div class="alert alert-<%= bootstrap_alert(key) %>">
        <strong>
            <%= value %>
        </strong>
    </div>
<% end %>

app/views/layouts/_loading.html.erb
<div id="back">
    <div>
        <div id="load-box">
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
        </div>
        <p>Loading<span>...</span></p>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>bookmemoryphrase</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- bootstrapの導入 -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- fontawesome -->
    <script src="https://kit.fontawesome.com/c6599c59c4.js" crossorigin="anonymous"></script>

    <!-- googlefonts -->
    <link href="https://fonts.googleapis.com/css?family=Noto+Serif+JP&display=swap" rel="stylesheet">

  </head>

  <body>
    <%= render 'layouts/loading' %>
    <%= render 'layouts/flashes' %>
      <div class="title-top">
          <%= link_to('book memory phrase','/',class:"site-title") %>
      </div>
      <div id="title-nav">
          <div class="cp_cont">
            <input type="checkbox" id="cp_toggle03">
            <div class="cp_mobilebar">
              <label for="cp_toggle03" class="cp_menuicon">
                <span></span>
              </label>
            </div>
            <header class="cp_offcm03">
              <nav>
                <ul>
                  <li>
                    <%= link_to('/') do %>
                      <i class="fas fa-home"></i>
                    <% end %>
                  </li>
                  <% if user_signed_in? %>
                    <li>
                      <%= link_to(posts_path) do %>
                        <i class="fas fa-book-open"></i>
                      <% end %>
                    </li>
                    <li>
                      <%= link_to(new_post_path) do %>
                        <i class="fas fa-pen-nib"></i>
                      <% end %>
                    </li>
                    <li>
                      <%= link_to(users_show_path) do %>
                        <i class="fas fa-user"></i>
                      <% end %>
                    </li>
                    <li>
                      <%= link_to(users_sign_out_path) do %>
                        <i class="fas fa-sign-out-alt"></i>
                      <% end %>
                    </li>
                  <% else %>
                    <li>
                      <%= link_to(new_user_registration_path) do %>
                        <i class="fas fa-user-plus"></i>
                      <% end %>
                    </li>
                    <li>
                      <%= link_to(users_sign_in_path) do %>
                        <i class="fas fa-sign-in-alt"></i>
                      <% end %>
                    </li>
                  <% end %>
                </ul>
              </nav>
            </header>
          </div>
      </div>
      <div id = "overwrap">
        <%= yield %>
      </div>
      <footer>
        <div>Contact and reference links</div>
        <div>
            <a href="https://qiita.com/soehina" target="_blank"><i class="fab fa-quora fa-lg"></i></a>
            <a href="https://github.com/soehina/book_memory_phrase" target="_blank"><i class="fab fa-github fa-lg"></i></a>
            <a href="https://twitter.com/hukushima_nem" target="_blank"><i class="fab fa-twitter fa-lg"></i></a>
        </div>
      </footer>
      <!-- bootstrap -->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>
  </body>
</html>